services:
  postgres:
    image: postgres:16-alpine
    container_name: cdc-postgres
    environment:
      POSTGRES_USER: cdc_user
      POSTGRES_PASSWORD: cdc_password
      POSTGRES_DB: enterprise_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres -c config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cdc_user -d enterprise_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cridix
